version: '3.3'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=authuser
      - POSTGRES_PASSWORD=authpassword
    network_mode: host

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/auth
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - DATASOURCE_USER=authuser
      - DATASOURCE_PASSWORD=authpassword
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    network_mode: host
